version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo build statred on 'date'
      - cp index.html /var/www/html/
  post_buils:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - /var/www/html/index.html
